version: "3.8"


services:
  ####################################
  # Atomic Microservice: account-service
  ####################################
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    restart: always
    # env_file:
    #   - "user_dev.env"
    ports:
      - "30000:8080"
  ####################################
  # Atomic Microservice: task-management-service
  ####################################
  task-management-service:
    build:
      context: ./task-management-service
      dockerfile: Dockerfile
    restart: always
    # env_file:
    #   - "user_dev.env"
    ports:
      - "30001:8080"
  ####################################
  # Atomic Microservice: employee-service
  ####################################
  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    restart: always
    # env_file:
    #   - "user_dev.env"
    ports:
      - "30002:8080"
  ####################################
  # Atomic Microservice: comments-service
  ####################################
  comments-service:
    build:
      context: ./comments-service
      dockerfile: Dockerfile
    restart: always
    # env_file:
    #   - "user_dev.env"
    ports:
      - "30004:8080"
  ####################################
  # Atomic Microservice: behavioral-analysis-service
  ####################################
  behavioral-analysis-service:
    build:
      context: ./behavioral-analysis-service
      dockerfile: Dockerfile
    restart: always
    # env_file:
    #   - "user_dev.env"
    ports:
      - "30007:8080"
  ####################################
  # Atomic Microservice: insidoors-frontend
  ####################################
  insidoors-frontend:
    build:
      context: ./insidoors-frontend
      dockerfile: Dockerfile
    restart: always
    # env_file:
    #   - "user_dev.env"
    ports:
      - "30008:3000"
  ####################################
  # Composite Microservice: notification-service
  ####################################
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    restart: always
    env_file:
     - "dev.env"
    ports:
      - "30009:8080"